"""Initial migration: add devices, users, and healthchecks tables

Revision ID: 944985581fc2
Revises: 
Create Date: 2025-11-17 08:00:03.387492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944985581fc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('certificate_serial', sa.String(length=255), nullable=False),
    sa.Column('certificate_pem', sa.Text(), nullable=False),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('certificate_serial')
    )
    op.create_table('healthchecks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='healthy', nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthchecks_device_id'), 'healthchecks', ['device_id'], unique=False)
    op.create_index(op.f('ix_healthchecks_reported_at'), 'healthchecks', ['reported_at'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index(op.f('ix_healthchecks_reported_at'), table_name='healthchecks')
    op.drop_index(op.f('ix_healthchecks_device_id'), table_name='healthchecks')
    op.drop_table('healthchecks')
    op.drop_table('devices')
    # ### end Alembic commands ###
